### ISSUE TITLE
sample code snippets have invalid ref to ZoweZLUX 

### ISSUE THREAD

**Issue by philippe-richard** [zowe/workshop-user-browser-app#5]
when running the tutorial, i found a number of typos in chapter:
Adding your Dataservice to the App:
https://github.com/zowe/workshop-user-browser-app#adding-your-dataservice-to-the-app
the snippet of code reads:
"let uri = this.filter ? ZoweZLUX.uriBroker.pluginRESTUri....."
in fact ZoweZLUX should be replaced by rocketMVD (2 instances), otherwise npm run-script start will fail compilation with error msg:
ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts
./src/app/userbrowser-component.ts
[tsl] ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts(48,29)
TS2304: Cannot find name 'ZoweZLUX'.

ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts
./src/app/userbrowser-component.ts
[tsl] ERROR in /X9/var/zowe/0.9.0/workshop-user-browser-app/webClient/src/app/userbrowser-component.ts(48,156)
TS2304: Cannot find name 'ZoweZLUX'.
There are similar issues further down the tutorial from other code snippets belonging to file userbrowser-component.ts
The same issue applies to https://github.com/zowe/workshop-starter-app.git...
in file /X9/var/zowe/0.9.0/workshop-starter-app/webClient/src/app/workshopstarter-component.ts
All references to ZoweZLUX should be changed to RocketMVD
Also pluginManager should be changed to PluginManager
Also the /X9/var/zowe/0.9.0/zlux-example-server/deploy/instance/ZLUX/pluginStorage/org.openmainframe.zowe.workshop-starter/tasks/report-bug.json                                                   is created but is not tagged as ASCII, so when you run the user-browser-app you get an error message in the zowe log: com.rs.configjs.data WARNING] - Exception when parsing JSON. File=/X9/var/zowe/0.9.0/zlux-example-server/deploy/instance/ZLUX/pluginSStorage/org.openmainframe.zowe.workshop-starter/tasks/report-bug.json. Error=SyntaxError: Unexpected token # in JSON at position 0

**Comment by 1000TurquoisePogs** [comment]
Thank you for trying out the tutorial and giving feedback!
Actually, what happened here is that RocketMVD was renamed to ZoweZLUX in zowe 0.9.1, but the workshop wasn't tagged to show what release it corresponded to.
I've now tagged the commits that correspond to certain zowe releases: https://github.com/zowe/workshop-user-browser-app/releases

So, you can see here that we switched the variable name: https://github.com/zowe/workshop-user-browser-app/commit/5f5a0ccc5b106bd02e1c46ab092bd2a6f069f9ba

We're still trying to Zowe-ify some IDs & variables before getting to 1.0, so these sorts of changes should settle down by then.

**Comment by 1000TurquoisePogs** [comment]
Closing with the intent to solve this via https://github.com/zowe/zlux/issues/54
